import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { TypewriterEffectSmoothDemo } from "@/components/Name";
import { Spotlight } from "@/components/ui/Spotlight";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="relative flex gap-10  bg-black/[0.96]  bg-grid-white/[0.02]">
          <div className="py-8 px-8">
            <TypewriterEffectSmoothDemo />
          </div>

          <div>
            <Navbar />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
